### ISSUE TITLE
How to deal the problem——Traceback (most recent call last):   File "object_detection_tf.py", line 201, in <module>     p.start()

### ISSUE THREAD

**Issue by dapsjj** [scotthuang1989/object_detection_with_tensorflow#3]
When I run your code,there is a problem.Traceback (most recent call last):   File "object_detection_tf.py", line 201, in <module>   
  p.start()
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by scotthuang1989** [comment]
in order to make sure we are using the same code. I push a v0.1 version a few minutes ago, can you try that version to see if yo still got the same issue?

**Comment by dapsjj** [comment]
There are two branches,master and multithread.I should use which one?
In branch multithread I can see two python files.
They are object_detection_tf_multiprocessing.py and object_detection_tf_multithread.py
I should use which one ?

When I use object_detection_tf_multithread.py,it is worked.

But when I use object_detection_tf_multiprocessing.py.It is not worked.
The error message is :Traceback (most recent call last):
  File "object_detection_tf_multiprocessing.py", line 179, in <module>
    main()
  File "object_detection_tf_multiprocessing.py", line 157, in main
    p.start()
  File "E:\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "E:\Anaconda3\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "E:\Anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "E:\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\Anaconda3\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "E:\Anaconda3\lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
EOFError: Ran out of input
image worker start

**Comment by scotthuang1989** [comment]
you should use multiprocessing version. because performance of multithread version is not good. 
but if mutithread is working but multiprocess is not, I think maybe this is because the python multi process is having compatible issue with windows. I don't have windows environment in hand. I will get back to you when I try it on windows.  mean while you can search on online about muti-processing on windows, there are may solution on line.

**Comment by dapsjj** [comment]
Thank you very much!When you try it on windows.Look forward to your reply.

**Comment by dippac** [comment]
Hello, author, I ran the project in windows environment, the same problem occurred.I have read the relevant information, still can not solve the problem.

**Comment by scotthuang1989** [comment]
sorry for this. but all my work is done under linux. I don't have time to setup a windows environment to debug this for now. been super busy
